### ISSUE TITLE
Blender 2.8 Branch

### ISSUE THREAD

**Issue by stilobique** [overmindstudios/BlenderUpdater#10]
Really Great tools to simply try and update the latest version. Adding a way to update all branch or only the 2.8 branch can be a great thing.

Not really an issue, it's a feature request :) .

**Comment by tobkum** [comment]
And rightly so - I'll look into it soon when I have more time!

**Comment by tobkum** [comment]
https://github.com/overmindstudios/BlenderUpdater/commit/6a8d2422edb6dba8c407e88ffea857448dbdb691 added the Blender 2.8 branch. Not usable yet, but getting there :)
