### ISSUE TITLE
I can't get it freezed

### ISSUE THREAD

**Issue by OgierM** [overmindstudios/BlenderUpdater#20]
Neither your version nor my fork... I just get this 
![image](https://user-images.githubusercontent.com/29630575/45890881-58736f80-bdc4-11e8-9c00-1a717edf9a90.png)

From screenshotting the pyinstaller window I can verify that the cause is that it can't find QT-stuff from Qt.py
How did you install Qt.py?

**Comment by OgierM** [comment]
Okay, I got it working by removing Qt.py and just using PySide2 normally instead

**Comment by tobkum** [comment]
Hey @OgierM - thanks for the headsup anyways!
I commited a fix that checks if we are running from a frozen binary (then we import PySide2) or from a Python script (import Qt.py in that case).
