### ISSUE TITLE
Two crashes

### ISSUE THREAD

**Issue by Irmitya** [overmindstudios/BlenderUpdater#22]
1. I started the program, clicked [Version Check] and got a warning about needing a valid directory. 
Clicked the folder icon then clicked the explorer window thing that pops up and it crashed. 
_(happens when trying to version check on a blank name first)_

2. Started the program, clicked the folder and selected my main Blender folder _(because I always use daily)_.
Clicked [Version Check] and selected the Blender version I use. 
Program downloaded Blender and etc, then it closed.  I figured that's how it works. 
To make sure, I made a blank folder and tried again.  It crashed without warning because I was running the Blender.exe that's already in the folder.

Now that I figured out how to get it to work without crashing, it'll be super convenient.

**Comment by tobkum** [comment]
Hey echerry93! Can you post the BlenderUpdater.log that has been generated?

**Comment by echerry93** [comment]
[BlenderUpdater.log](https://github.com/overmindstudios/BlenderUpdater/files/2508609/BlenderUpdater.log)
