### ISSUE TITLE
Malwarebytes vs. BlenderUpdater.exe

### ISSUE THREAD

**Issue by Harvester62** [overmindstudios/BlenderUpdater#25]
This is not really a "bug" but starting from this morning blenderupdater.exe version 1.9.3 is seen by Malwarebytes (antimalware program) as containing a malware called Adware.IStartSurf and therefore it's being moved to the quarantine or deleted. I was able to add some exclusions to Malwarebytes and now it doesn't remove the program but asks for permissions to run it. This could also be a false positive.

**Comment by tobkum** [comment]
I do check every release with Kaspersky Anti Virus, so that is a false positive. I'm not sure what I can do regarding that though...
Thanks for the heads up!
