### ISSUE TITLE
It has stopped working since 20/12/2018

### ISSUE THREAD

**Issue by juangea** [overmindstudios/BlenderUpdater#26]
That´s the problem.

It has stopped working since 20/12/2018

I open it, configure the folder, it recognizes build on the site and version but when I press the build button to download it, it does nothing.

Cheers!

**Comment by tobkum** [comment]
Thanks for the report, I suspect they changed around a few paths. Will
investigate on the weekend!

Cheers,
-T

**Comment by tobkum** [comment]
fixed with commit #5ea6bf2

**Comment by OgierM** [comment]
Was wondering myself; just merged your commit.
Was it really just the first character being truncated? And if yes - what did change with names lol

**Comment by tobkum** [comment]
Haven't had the time to investigate what exactly happened, but hey - it
works for now :-)
Cheers, T
