### ISSUE TITLE
Error: No module named 'requests'

### ISSUE THREAD

**Issue by nickmadedesign** [overmindstudios/BlenderUpdater#27]
Hi,

I'm getting:

`Traceback (most recent call last):
  File "BlenderUpdater.py", line 35, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Using python3 via brew with the following command:

`python3 BlenderUpdater.py`

Any ideas?

Thanks!

**Comment by tobkum** [comment]
Heya!
Make sure that you have the requests module installed on your system when
you want to run it from source code ('pip install requests'). This is also
applicable to all the other imported modules.
Let me know if this helps!
Cheers,
-T

**Comment by nickmadedesign** [comment]
Hi Tobias,

I appreciate you replying. I'm running with Python3 via homebrew on OSX, so I had to run 'pip3 install requests'. I went through a few dependencies but now I've hit another road block:

`Traceback (most recent call last):
  File "BlenderUpdater.py", line 38, in <module>
    import mainwindow
  File "/Users/mothership/Downloads/Nick Made/BlenderUpdater-1.9.4/mainwindow.py", line 11, in <module>
    from Qt import QtCore, QtGui, QtWidgets`

and pip3 install Qt results in:

`Collecting qt
  Could not find a version that satisfies the requirement qt (from versions: )
No matching distribution found for qt`

I'm not sure if you or anyone else has experienced before.

Thanks!

**Comment by tobkum** [comment]
Hey!
I don't use a Mac here, so I cannot reproduce that error unfortunately...
Another alternative would be using my command line version over at https://github.com/overmindstudios/BlenderUpdaterCLI - this one doesn't need the Qt dependency.

Sorry for not being able to resolve that one :-/

Cheers,
-T

**Comment by nickmadedesign** [comment]
No worries, that worked better. For those that might come across this with Mac & brew in the future, `pip3 install colorama` and `pip3 install progress` along with the standard CLI command with python3 got me going.

Thanks!
