### ISSUE TITLE
Updater displays false 'Version already installed' notification when interrupted

### ISSUE THREAD

**Issue by OfficialKris** [overmindstudios/BlenderUpdater#31]
The current behavior is:

- Open the updater
- Run the updater
- Updater gets interupted (See #30)
- Restart updater manually
- Check for update
- Select update
- Notification displays showing 'Version already installed'

Maybe more debugging needs to be done regarding if the updater succeded in the case of the interuption But taking the side of it didn't, this notfication is false.

**Comment by tobkum** [comment]
Thanks for the reports, valid points. I'll look into them asap!
