### ISSUE TITLE
Squeezed layout at 150% scaling on Windows 10

### ISSUE THREAD

**Issue by DabuXian** [overmindstudios/BlenderUpdater#36]
Looks like the app has trouble adjusting its layout with 150% scaling on Windows, which is the default on 4K screens. 

![image](https://user-images.githubusercontent.com/4173488/93669028-3be09f80-fa91-11ea-9cf5-f479e4b2e53c.png)

**Comment by tobkum** [comment]
Thanks for reporting! Can you check the newest build and let me know if this works?

**Comment by DabuXian** [comment]
Better, but still getting cut off in some places a little bit!

![image](https://user-images.githubusercontent.com/4173488/93709139-28d6d980-fb3c-11ea-881a-0b7df85ca019.png)
![image](https://user-images.githubusercontent.com/4173488/93709149-2e342400-fb3c-11ea-9f19-267270604872.png)

**Comment by tobkum** [comment]
I added another fix and replaced the file in the release - hope it works now!

**Comment by DabuXian** [comment]
Yep, now it's perfect! 👍

**Comment by tobkum** [comment]
Great, thanks for the report!
