### ISSUE TITLE
builder.blender.org site has changed

### ISSUE THREAD

**Issue by Thane5** [overmindstudios/BlenderUpdater#38]
Looks like the build site got an update recently, and now the selection window in this updater is cluttered and unreadable.

![Screenshot 2021-05-19 095148](https://user-images.githubusercontent.com/13683581/118776114-eced4300-b887-11eb-89a1-9f204e6909f8.png)

**Comment by tobkum** [comment]
Thanks for reporting, will look into it asap!

**Comment by Harvester62** [comment]
Thank you for looking into this issue because your tool is key to my  daily updates of the developing branches. Hope you can fix it.

**Comment by tobkum** [comment]
Should be fixed - lmk if you have any further issues!

**Comment by Harvester62** [comment]
Perfect! Thank you very much!
