### ISSUE TITLE
Blank choice after pressing Version Check on start screen

### ISSUE THREAD

**Issue by piotrnikov** [overmindstudios/BlenderUpdater#44]
Hello!
There seems to be a problem since the last couple of days.
I get this (on two of my Win11 gears):
![Screenshot 2021-11-26 140454](https://user-images.githubusercontent.com/28474540/143585739-1e2d5ec2-0e35-400a-8732-9de90365213e.png)
So basically a blank screen.
Am I the only one?
Thanks!
Piotr
PS And thanks again for a very super convenient utility!!!

**Comment by Harvester62** [comment]
Nope! I have the same problem here on Windows 10 Pro, 64 bit.

**Comment by EdwHopper** [comment]
Same here, on two different pc's.

**Comment by tobkum** [comment]
Will check over the weekend, thanks for reporting!

**Comment by BAndiT1983** [comment]
Format of data probably changed and name is not included as text part. Quick fix for now ->

Lines 336-343:
```python
parts = element.text.split(" - ")
output = {}
output["date"] = clean(parts[0])
#output["name"] = clean(parts[1])
output["hash"] = clean(parts[1])
output["type"] = clean(parts[2])
output["size"] = clean(parts[3])
return output
```

Line 370:
```python
info["version"] = name + "_" + description_data["hash"]
```

**Comment by tobkum** [comment]
Thanks @BAndiT1983 - incorporated your fix, works again! New build up in a few minutes!

**Comment by BAndiT1983** [comment]
No problem, glad that it helped.
