### ISSUE TITLE
Empty build list

### ISSUE THREAD

**Issue by piotrnikov** [overmindstudios/BlenderUpdater#46]
Hello!
It seems something changed again. I'm getting this since this morning:
![image](https://user-images.githubusercontent.com/28474540/159857418-c00a1823-851d-4acf-9285-9771ce69d6e2.png)
Basically an empty list :)
Am I the only one?
Thanks!

Piotr

**Comment by tobkum** [comment]
thanks for reporting, will look into it asap!

**Comment by tobkum** [comment]
@piotrnikov - can you test the latest release? It should work again.

**Comment by piotrnikov** [comment]
Hi @tobkum !
Yes it seems to work again.
Thanks so much!!
