### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by piotrnikov** [overmindstudios/BlenderUpdater#47]
Hi again, and sorry to bother you with something so trivial, but this window now appears when I launch BlenderUpdater:
![Screenshot 2022-04-02 110412](https://user-images.githubusercontent.com/28474540/161381180-ad1e1bab-474d-4b41-acc6-faf8fcc6b733.png)
Pressing ok opens the usual program window normally.
Any ideas how to not have that window popup at startup?
Thanks!

Piotr

**Comment by tobkum** [comment]
Thanks for reporting, I'll check tomorrow!

**Comment by tobkum** [comment]
@piotrnikov - should work now, no need to update. Just a little error on my side regarding the release tag :) Thanks!
