### ISSUE TITLE
Buttons overlapping

### ISSUE THREAD

**Issue by Thane5** [overmindstudios/BlenderUpdater#48]
![image](https://user-images.githubusercontent.com/13683581/181511688-e20aaa37-7bf7-4cc7-b4db-ba5f7f61ab7c.png)

With so many download options, the filter buttons at the bottom are almost impossible to press.

**Comment by tobkum** [comment]
I'll have a look asap! Thanks for reporting!

**Comment by tobkum** [comment]
Let me know if this works now!

**Comment by Harvester62** [comment]
It works, thank you for fixing it!
